/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import LinZoznam.Osoba;
import LinZoznam.*;
import java.io.DataOutputStream;


import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.Serializable;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Marcel
 */
public class JForm extends javax.swing.JFrame implements Serializable{

    LinZoznam pomZoz;
    String fileLibrary;
    Polozka zac;
    public JForm() {
        fileLibrary="D:\\SKOLA\\ZU\\4.SEMESTER\\Udajove struktury\\Semestralka1\\src\\a.txt";
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVypis = new javax.swing.JTextArea();
        btnPridaj1 = new javax.swing.JButton();
        btnOdober = new javax.swing.JButton();
        btnPridaj = new javax.swing.JButton();
        btnOdober2 = new javax.swing.JButton();
        btnUspo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVytvor = new javax.swing.JButton();
        btnZmaz = new javax.swing.JButton();
        btnKon = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtVypis.setColumns(20);
        txtVypis.setRows(5);
        jScrollPane1.setViewportView(txtVypis);

        btnPridaj1.setText("Pridaj na začiatok");
        btnPridaj1.setEnabled(false);
        btnPridaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridaj1ActionPerformed(evt);
            }
        });

        btnOdober.setText("Odober zo začiatku");
        btnOdober.setEnabled(false);
        btnOdober.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdoberActionPerformed(evt);
            }
        });

        btnPridaj.setText("Pridaj na koniec");
        btnPridaj.setEnabled(false);
        btnPridaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridajActionPerformed(evt);
            }
        });

        btnOdober2.setText("Odober podľa parametra");
        btnOdober2.setEnabled(false);
        btnOdober2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdober2ActionPerformed(evt);
            }
        });

        btnUspo.setText("Usporiadaj");
        btnUspo.setEnabled(false);
        btnUspo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUspoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LINEARNY ZOZNAM");
        jLabel1.setEnabled(false);

        btnVytvor.setText("Vytvor zoznam");
        btnVytvor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVytvorActionPerformed(evt);
            }
        });

        btnZmaz.setText("Zmaz zoznam");
        btnZmaz.setEnabled(false);
        btnZmaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZmazActionPerformed(evt);
            }
        });

        btnKon.setText("Koniec");
        btnKon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnLoad.setText("Load");
        btnLoad.setEnabled(false);
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnUspo)
                            .addGap(71, 71, 71))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(btnPridaj))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnPridaj1)
                                                    .addComponent(btnOdober)))
                                            .addGap(53, 53, 53))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnOdober2)
                                            .addGap(35, 35, 35))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnVytvor)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnZmaz)
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnKon)
                        .addGap(129, 129, 129)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnLoad))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPridaj1)
                        .addGap(11, 11, 11)
                        .addComponent(btnOdober)
                        .addGap(1, 1, 1)
                        .addComponent(btnPridaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOdober2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUspo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnZmaz)
                            .addComponent(btnVytvor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(btnKon)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * vytvori instanciu zoznamu
 * @param evt 
 */
    private void btnVytvorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVytvorActionPerformed
       
        pomZoz = new LinZoznam();
       btnVytvor.setEnabled(false);
        btnZmaz.setEnabled(true);
        btnPridaj.setEnabled(true);
        btnPridaj1.setEnabled(true);
        btnOdober.setEnabled(true);
        btnOdober2.setEnabled(true);
        btnUspo.setEnabled(true);
        btnSave.setEnabled(true);
        btnLoad.setEnabled(true);
    }//GEN-LAST:event_btnVytvorActionPerformed
/**
 * Zmaze instanciu zoznamu
 * @param evt 
 */
    private void btnZmazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZmazActionPerformed
        pomZoz=null;
        btnVytvor.setEnabled(true);
        btnZmaz.setEnabled(false);
        btnPridaj.setEnabled(false);
        btnPridaj1.setEnabled(false);
        btnOdober.setEnabled(false);
        btnOdober2.setEnabled(false);
        btnUspo.setEnabled(false);
        btnSave.setEnabled(false);
        btnLoad.setEnabled(false);
        txtVypis.setText(" ");
    }//GEN-LAST:event_btnZmazActionPerformed
/**
 * Prida prvok do existujuceho zozanamu
 * @param evt 
 */
    private void btnPridaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridaj1ActionPerformed
        String data;
int vek;
        while(true){
                try{
                  data=JOptionPane.showInputDialog("Zadajte meno:");
                    for(int k=0;k<data.length();k++){
                        if(((data.charAt(k)<64)&&(data.charAt(k)>90))||((data.charAt(k)<97)&&(data.charAt(k)>122))){
                            throw new IllegalStateException();                    }
                    }
                    break;
                } catch(IllegalStateException e) {
                    JOptionPane.showMessageDialog(null,"Zadajte správne meno obsahujuce iba pismená bez diakritiky","ERROR",JOptionPane.WARNING_MESSAGE);
                }
            }
            while(true){
                try{
                  vek=Integer.parseInt(JOptionPane.showInputDialog("Zadajte vek:"));
                    break;
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"Zadajte správny vek","ERROR",JOptionPane.WARNING_MESSAGE);
                }
            }    
        pomZoz.vlozNaZac(new Osoba(data,vek));
                
        txtVypis.setText(pomZoz.toString());
    }//GEN-LAST:event_btnPridaj1ActionPerformed
/**
 * Odoberie prvok z existujuceho zoznamu
 * @param evt 
 */
    private void btnOdoberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdoberActionPerformed
       if(pomZoz.getPocet()!=0){
           try {
               pomZoz.odoberZoZac();
               for(int i=0;i<pomZoz.getPocet()+1;i++){
                   txtVypis.setText("");
                   txtVypis.setText(pomZoz.toString());
                   
               }
           } catch (Exception ex) {
               Logger.getLogger(JForm.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       else{
       JOptionPane.showMessageDialog(rootPane, "V zozname niesu prvky!!! ");
       }
        
    }//GEN-LAST:event_btnOdoberActionPerformed
/**
 * Prida prvok na koniec existujuceho zoznamu
 * @param evt 
 */
    private void btnPridajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridajActionPerformed
String data;
int vek;
        while(true){
                try{
                  data=JOptionPane.showInputDialog("Zadajte meno:");
                    for(int k=0;k<data.length();k++){
                        if(((data.charAt(k)<64)&&(data.charAt(k)>90))||((data.charAt(k)<97)&&(data.charAt(k)>122))){
                            throw new IllegalStateException();                    }
                    }
                    break;
                } catch(IllegalStateException e) {
                    JOptionPane.showMessageDialog(null,"Zadajte správne meno obsahujuce iba pismená bez diakritiky","ERROR",JOptionPane.WARNING_MESSAGE);
                }
            }
            while(true){
                try{
                  vek=Integer.parseInt(JOptionPane.showInputDialog("Zadajte vek:"));
                    break;
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"Zadajte správny vek","ERROR",JOptionPane.WARNING_MESSAGE);
                }
            }    
        pomZoz.vlozNaKon(new Osoba(data,vek));
       
                
        txtVypis.setText(pomZoz.toString());
                           
    }//GEN-LAST:event_btnPridajActionPerformed
/**
 * Skonci program
 * @param evt 
 */
    
    private void btnKonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKonActionPerformed
/**
 * Ulozi zoznam
 * @param evt 
 */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
           try{
int i=0;
                    FileOutputStream abc=new FileOutputStream("vystup.txt");
                    DataOutputStream s =new DataOutputStream(abc);   
    try {
        s.writeChars(pomZoz.toString());
    } catch (IOException ex) {
        Logger.getLogger(JForm.class.getName()).log(Level.SEVERE, null, ex);
    }
                        i++;
                    }catch(FileNotFoundException e){
                    JOptionPane.showMessageDialog(null,"Chyba pri načítaní udajov.");
                }
  
      
    }//GEN-LAST:event_btnSaveActionPerformed
/**
 * Nacita zoznam
 * @param evt 
 */
    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
    String riadok;
  int pomCis;
       try{

                    FileReader abc=new FileReader(fileLibrary);
                    Scanner in=new Scanner(abc);
                    while(in.hasNext()){
                        riadok=in.nextLine();
                        pomCis=Integer.parseInt(riadok);
                        pomZoz.vlozNaZac(new Osoba(pomCis));
                       
                        }

                    }catch(FileNotFoundException e){
                    JOptionPane.showMessageDialog(null,"Chyba pri načítaní udajov.");
                }
       txtVypis.setText(pomZoz.toString());

    }//GEN-LAST:event_btnLoadActionPerformed
/**
 * Usporiada zoznam podla veku
 * @param evt 
 */
    private void btnUspoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUspoActionPerformed
        try {
            pomZoz.bubleSort();
        } catch (Exception ex) {
            Logger.getLogger(JForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtVypis.setText(pomZoz.toString());
    }//GEN-LAST:event_btnUspoActionPerformed
/**
 * Odobere podla hodnoty
 * @param evt 
 */
    private void btnOdober2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdober2ActionPerformed
        String riadok; 
        riadok=JOptionPane.showInputDialog("Zadajte cislo prvku ktore sa ma zrusit :");
        try {
            int cislo=Integer.parseInt(riadok);
              pomZoz.removeToPosicion(cislo);
              
         
            
            
        } catch (Exception ex) {
            Logger.getLogger(JForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       txtVypis.setText(pomZoz.toString());
         
    }//GEN-LAST:event_btnOdober2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JForm().setVisible(true);
            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKon;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnOdober;
    private javax.swing.JButton btnOdober2;
    private javax.swing.JButton btnPridaj;
    private javax.swing.JButton btnPridaj1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUspo;
    private javax.swing.JButton btnVytvor;
    private javax.swing.JButton btnZmaz;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtVypis;
    // End of variables declaration//GEN-END:variables
}
